In [1]:
import pickle

In [21]:
import pandas as pd
import numpy as np

In [3]:
with open('synthesisStatistics.pickle', 'rb') as pickle_file:
    content = pickle.load(pickle_file)

In [4]:
with open('origAIGNodesDict.pickle', 'rb') as pickle_file:
    content = pickle.load(pickle_file)

In [5]:
import torch

In [6]:
torch.load('ac97_ctrl_syn706_step0.pt')

Data(and_nodes=11464, desName=[1], edge_index=[2, 25065], edge_type=[25065], longest_path=11, node_id=[15940], node_type=[15940], not_edges=14326, num_inverted_predecessors=[15940], pi=2339, po=2137, stepID=[1], synID=[1], synVec=[20])

In [7]:
data = torch.load('i2c_syn1204_step0.pt')

In [8]:
a = data.to_dict()

In [9]:
import io

with open('ac97_ctrl_syn706_step0.pt', 'rb') as f:
    buffer = io.BytesIO(f.read())
    print(buffer)

In [10]:
a['pi'].numpy()

array(177, dtype=int64)

In [11]:
a.keys()

dict_keys(['and_nodes', 'desName', 'edge_index', 'edge_type', 'longest_path', 'node_id', 'node_type', 'not_edges', 'num_inverted_predecessors', 'pi', 'po', 'stepID', 'synID', 'synVec'])

In [34]:
a['edge_index'].numpy()[0], a['edge_index'].numpy()[1]

(array([ 177,  177,  178, ..., 1472, 1472, 1473], dtype=int64),
 array([   6,    7,    4, ...,  176,  353, 1472], dtype=int64))

In [22]:
np.unique(a['edge_type'].numpy())

array([0, 1], dtype=int64)

In [17]:
a['synVec'].numpy()

array([3, 0, 4, 4, 6, 1, 5, 5, 1, 3, 2, 4, 0, 6, 1, 0, 6, 2, 1, 4],
      dtype=int64)

In [28]:
np.array(a['node_id']).shape

(1474,)

In [35]:
a['synID']

[1204]

In [ ]:
p.head()

In [ ]:
p.to_csv('synthesisStatistics.csv')

In [ ]:
p.columns

In [ ]:
data_bible = {}
for i in p.columns:
    data_bible[i] = {}

In [ ]:
data_bible

In [ ]:
for i in range(len(data_bible)):
    for j in range(1500):
        data_bible[p.columns[i]][j] = [p[p.columns[i]][0][j], p[p.columns[i]][1][j], p[p.columns[i]][2][j], p[p.columns[i]][3][j], p[p.columns[i]][4][j]]

In [ ]:
i = 'Rocket_csr'
j = 0
[p[i][0][j], p[i][1][j], p[i][2][j], p[i][3][j], p[i][4][j]]

In [ ]:
data_bible

In [ ]:
import json

with open('datapoints.json', 'w') as fp:
    json.dump(data_bible, fp)

In [ ]:
## Splitting the training and testing data as a normal distribution of number of points/recipes picked per design vs 
## the number of designs per data point. The designs picked at each step can again be randomized so that we get a very nice 
## and even split of data

In [ ]:
import numpy as np

mean = 300
std_dev = 30
points = 48

arr = np.random.normal(mean, std_dev, points)
arr = arr.astype(int)
print(arr)

In [ ]:
a = [i for i in range(1,10)]
print(a)
np.random.choice(a, size=3, replace=False)

In [ ]:
test_dict = {}
train_dict = {}
count = 0
for i in data_bible:
    indices = [i for i in range(1, 1501)]
    ind = np.random.choice(indices, size=arr[count], replace=False)
    for j in ind:
        if i not in test_dict:
            test_dict[i] = {}
            test_dict[i][str(j)] = data_bible[i][j-1]
        test_dict[i][str(j)] = data_bible[i][j-1]
    count+=1

In [ ]:
len(test_dict['Rocket_csr'])

In [ ]:
test_dict['Rocket_csr']

In [ ]:
import json

with open('test_datapoints.json', 'w') as fp:
    json.dump(test_dict, fp)

In [ ]:
train_data = {}
for i in data_bible:
    train_data[i] = {}
    for j in range(1500):
        if str(j+1) not in test_dict[i]:
            train_data[i][str(j+1)] = data_bible[i][j]

In [ ]:
len(train_data['Rocket_csr'])

In [ ]:
import json

with open('train_datapoints.json', 'w') as fp:
    json.dump(train_data, fp)